[tool.poetry]
name = "cicd-test"
version = "1"
description = "desc"
authors = ["Your Name <you@example.com>"]
license = "basic"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
