name: SBOM Generator

on:
  release:
    types: [ published ]

run-name: SBOM Generation for  ${{ github.event.release.tag_name }} published by @${{ github.actor }}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - uses: actions/checkout@v4
      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with: 
          path: ${{ steps.sbom.outputs.fileName }}
          name: "SBOM"
      - name: update to release asset
        uses: echapmanFromBunnings/upload-release-assets@1.3
        with:          
          releaseTag: ${{ github.event.release.tag_name }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ steps.sbom.outputs.fileName }}
