name: Deploy Pages

on:
  push:
    branches: [ "main" ]

jobs:
  pages-deploy:
    environment:
      name: github-pages
    runs-on: [ ubuntu-latest ]
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Publish Site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
