name: Manual - Add branch protection config to repository - by filter on topic

on:
  workflow_dispatch:
    inputs:
      filter-topic:
        description: "topic to filter on to collect repositories"
        required: true
      branch-rule-file-path:
        description: "path to file to collect rules to apply"
        required: true
        default: '.github/workflows/config/branch_protection/team-a.json'
      targeted-branch:
        description: "name of branch to apply protections to"
        required: true
      pat:
        description: "PAT with repo admin access for organisation"
        required: true
        default: PUT_PAT_HERE

jobs: 
  get-repos:
    runs-on: generic
    outputs:
      repojson: ${{ steps.get-repo.outputs.repojson }}
    steps:
      - name: get repos
        id: get-repo
        uses: echapmanFromBunnings/repository-query@v1.3
        with:
          repo-owner: JediSchools
          repo-token: ${{ inputs.pat }}
          topic-filter: '${{ inputs.filter-topic }}'
  
  add-branch-protection:
    runs-on: generic
    needs: get-repos
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-repos.outputs.repojson) }}
      max-parallel: 2
      fail-fast: false
    steps:
      - name: mask pat
        run: echo "::add-mask::${{ inputs.pat }}"
      - uses: actions/checkout@v4
      - name: Run Branch Protection
        uses: mistereechapman/update-branch-protection@1.0
        with:
          token: '${{ inputs.pat }}' 
          organisationName: ${{ matrix.owner }}
          repositoryName: ${{ matrix.name }}
          branchName: ${{ inputs.targeted-branch }}
          rulesPath: ${{ inputs.branch-rule-file-path }}
          action: set
