name: Sith Lords firing repo init

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: "SithLords.NodeJSApp"
          token: ${{ secrets.EVENTHUB_TOKEN }}
          repository: 'YOUR_ORG/EventHub.GitHub'
          client-payload: '{"repo": "${{ github.repository }}"}'
