name: Python cicd

on:
  push:
    branches:

      - main
      - development
  pull_request:
    types : [opened,synchronize]
  workflow_dispatch: 

jobs: 
  gitleaks: 
    name: Gitleaks(Secrets)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: action/checkout@v3
        with: 
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

