name: Python cicd

on:
  push:
    branches:

      - main
      - development
  pull_request:
    types : [opened,synchronize]
  workflow_dispatch: 

jobs: 
  gitleaks: 
    name: Gitleaks(Secrets)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .gitleaks.toml
  snyk:
    name: Snyk (Security & Dependencies)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-in-project: true
      - name: Check Poetry Version
        run: poetry --version
      - run: poetry install
      - name: Check Poetry Version
        run: poetry --version
      - name: Run Snyk to Check for Vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
      - name: Run Snyk to Check for Vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
  black:
    name: Black (Python Formatting)
    runs-on: ubuntu-latest
    steps:
      - name: Install Black and isort
        run: pip install black isort
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-in-project: true
          options: --check --verbose
      - name: Black
        uses: jpetrucciani/black-check@24.3.0
      - name: Run isort
        run: isort --profile black .
      - name: Check Formatting
        run: black --check --diff --verbose
